server:
  port: 8082
  servlet:
    context-path: /
spring:
  cache:
    cache-names: test
    caffeine:
      spec: recordStats
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches